-- Paris Pulse. Apply in Supabase SQL editor or supabase db reset.
create extension if not exists pgcrypto;
create table public.users (id uuid primary key references auth.users on delete cascade, email text not null, full_name text not null default '', role text not null default 'user' check(role in ('user','editor','admin')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create function public.is_editor() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.users where id=auth.uid() and role in ('editor','admin')) $$;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.users(id,email,full_name) values(new.id,coalesce(new.email,''),coalesce(new.raw_user_meta_data->>'full_name','')); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table public.communities (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, province text not null, country text not null, latitude double precision not null, longitude double precision not null, default_radius_km numeric not null default 3, active boolean not null default true);
create table public.locations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users on delete cascade, community_id uuid not null references communities, label text not null, address_line text not null, city text not null, province text not null, postal_code text not null default '', latitude double precision not null check(latitude between -90 and 90), longitude double precision not null check(longitude between -180 and 180), location_type text not null check(location_type in ('home','work','school','other')), is_primary boolean not null default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.interests (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, category text not null, description text, active boolean default true);
create table public.user_interests (user_id uuid references public.users on delete cascade,interest_id uuid references interests on delete cascade,primary key(user_id,interest_id));
create table public.official_sources (id uuid primary key default gen_random_uuid(), community_id uuid references communities, name text not null, organization text not null, source_type text not null, url text not null check(url ~ '^https://'), feed_url text, description text, authority_level text not null check(authority_level in ('official','official_agency','trusted_local_org','trusted_media','community_signal')), ingestion_type text not null check(ingestion_type in ('manual','rss','html','api','open_data')), ingestion_enabled boolean default false, refresh_interval_minutes integer default 60 check(refresh_interval_minutes>=15), last_checked_at timestamptz, last_success_at timestamptz, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.notices (id uuid primary key default gen_random_uuid(), community_id uuid not null references communities, source_id uuid not null references official_sources, external_id text, title text not null, slug text unique not null, summary text not null, body text, category text not null check(category in ('roads','construction','planning','recreation','facility','event','transit','downtown','public_notice','waste','storm','outage','emergency','other')), severity text not null check(severity in ('info','useful','important','urgent')), official_url text not null check(official_url ~ '^https://'), published_at timestamptz not null default now(), source_updated_at timestamptz, retrieved_at timestamptz not null default now(), verified_at timestamptz, start_at timestamptz,end_at timestamptz,expires_at timestamptz,address_text text,latitude double precision check(latitude between -90 and 90),longitude double precision check(longitude between -180 and 180),affected_radius_km numeric,affected_area_text text,city text not null,tags_json jsonb not null default '[]',verification_status text not null default 'draft' check(verification_status in ('draft','needs_review','verified','expired','rejected')),confidence_score numeric not null default 0 check(confidence_score between 0 and 1),is_sample boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index notices_external_unique on notices(source_id,external_id) where external_id is not null;
create table public.notice_locations(id uuid primary key default gen_random_uuid(),notice_id uuid not null references notices on delete cascade,latitude double precision not null,longitude double precision not null,radius_km numeric not null default 0,label text);
create table public.deadlines(id uuid primary key default gen_random_uuid(),notice_id uuid references notices on delete set null,community_id uuid not null references communities,title text not null,description text not null,category text not null,starts_at timestamptz,deadline_at timestamptz not null,official_url text not null check(official_url ~ '^https://'),latitude double precision,longitude double precision,source_id uuid not null references official_sources,verified_at timestamptz,is_sample boolean not null default false,created_at timestamptz default now());
create table public.user_notice_matches(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users on delete cascade,notice_id uuid not null references notices on delete cascade,location_id uuid references locations on delete set null,relevance_score numeric not null default 0,distance_km numeric,match_reasons_json jsonb not null default '[]',created_at timestamptz default now(),read_at timestamptz,saved_at timestamptz,dismissed_at timestamptz,unique(user_id,notice_id));
create table public.alert_preferences(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users on delete cascade,location_id uuid references locations on delete cascade,categories_json jsonb not null default '[]',radius_km numeric not null default 3 check(radius_km>=0),minimum_severity text not null default 'info',instant_enabled boolean default false,daily_digest_enabled boolean default true,weekly_digest_enabled boolean default false,deadline_reminders_enabled boolean default true,email_enabled boolean default true,push_enabled boolean default false,quiet_hours_start time,quiet_hours_end time,created_at timestamptz default now(),updated_at timestamptz default now());
create unique index alert_preferences_global on alert_preferences(user_id) where location_id is null;
create table public.deadline_reminders(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users on delete cascade,deadline_id uuid not null references deadlines on delete cascade,minutes_before integer not null check(minutes_before in (0,60,1440)),created_at timestamptz default now(),unique(user_id,deadline_id));
create table public.digest_runs(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users on delete cascade,digest_type text not null,generated_at timestamptz default now(),notice_ids_json jsonb default '[]',deadline_ids_json jsonb default '[]',delivery_status text not null);
create table public.ingestion_runs(id uuid primary key default gen_random_uuid(),source_id uuid not null references official_sources,started_at timestamptz default now(),completed_at timestamptz,status text not null,records_found integer default 0,records_created integer default 0,records_updated integer default 0,records_failed integer default 0,error_message text);
alter table public.users enable row level security;
alter table public.communities enable row level security;
alter table public.locations enable row level security;
alter table public.interests enable row level security;
alter table public.user_interests enable row level security;
alter table public.official_sources enable row level security;
alter table public.notices enable row level security;
alter table public.notice_locations enable row level security;
alter table public.deadlines enable row level security;
alter table public.user_notice_matches enable row level security;
alter table public.alert_preferences enable row level security;
alter table public.deadline_reminders enable row level security;
alter table public.digest_runs enable row level security;
alter table public.ingestion_runs enable row level security;
create policy users_read on users for select to authenticated using(id=auth.uid() or public.is_editor());
grant update(full_name) on users to authenticated;
revoke update on users from authenticated;
grant update(full_name) on users to authenticated;
create policy users_update on users for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy owner_access on locations for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy owner_access on user_interests for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy owner_access on user_notice_matches for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and (location_id is null or exists(select 1 from locations l where l.id=location_id and l.user_id=auth.uid())));
create policy owner_access on alert_preferences for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and (location_id is null or exists(select 1 from locations l where l.id=location_id and l.user_id=auth.uid())));
create policy owner_access on deadline_reminders for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy digest_read on digest_runs for select to authenticated using(user_id=auth.uid());
create policy public_read on communities for select using(active=true or public.is_editor());
create policy public_read on interests for select using(active=true or public.is_editor());
create policy public_read on official_sources for select using(active=true or public.is_editor());
create policy published_read on notices for select using(verification_status in ('verified','expired') or public.is_editor());
create policy deadline_read on deadlines for select using(verified_at is not null or is_sample or public.is_editor());
create policy notice_locations_read on notice_locations for select using(exists(select 1 from notices where notices.id=notice_id));
create policy editor_manage on communities for all to authenticated using(public.is_editor()) with check(public.is_editor());
create policy editor_manage on interests for all to authenticated using(public.is_editor()) with check(public.is_editor());
create policy editor_manage on official_sources for all to authenticated using(public.is_editor()) with check(public.is_editor());
create policy editor_manage on notices for all to authenticated using(public.is_editor()) with check(public.is_editor());
create policy editor_manage on notice_locations for all to authenticated using(public.is_editor()) with check(public.is_editor());
create policy editor_manage on deadlines for all to authenticated using(public.is_editor()) with check(public.is_editor());
create policy editor_manage on ingestion_runs for all to authenticated using(public.is_editor()) with check(public.is_editor());
create index on locations(user_id);
create index on user_notice_matches(user_id);
create index on notices(community_id,verification_status,published_at desc);
create index on notices(expires_at);
create index on deadlines(community_id,deadline_at);
create index on ingestion_runs(source_id,started_at desc);
create index on deadline_reminders(user_id);
create index on digest_runs(user_id);
